{{- if .Values.signingKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaol.fullname" . }}-signing-key
  labels:
    {{- include "vaol.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.signingKey.secretKey }}: {{ .Values.signingKey.privateKeyPEM }}
{{- end }}
